2014-09-30 21:36:18 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:36:18 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:36:19 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:36:19 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:36:20 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:36:20 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:36:21 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:36:21 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:36:59 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:36:59 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:37:00 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:37:00 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:37:00 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:37:00 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:37:00 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:37:00 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:37:52 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:37:52 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:37:53 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:37:53 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:37:53 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:37:53 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:37:53 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:37:53 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:37:53 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:37:53 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:37:54 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:37:54 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:37:54 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:37:54 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:37:54 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BooksController.php, line 19]
2014-09-30 21:37:54 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:38:19 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BookController.php, line 19]
2014-09-30 21:38:19 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:38:20 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BookController.php, line 19]
2014-09-30 21:38:20 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:38:21 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BookController.php, line 19]
2014-09-30 21:38:21 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:38:22 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/books/app/Controller/BookController.php, line 19]
2014-09-30 21:38:22 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/books/...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#2 /var/www/books/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/books/...', 19, Array)
#3 /var/www/books/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-30 21:38:35 Error: [MissingTableException] Table books for model Book was not found in datasource default.
Exception Attributes: array (
  'table' => 'books',
  'class' => 'Book',
  'ds' => 'default',
)
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Model/Model.php(3551): Model->setSource('books')
#1 /var/www/books/lib/Cake/Model/Model.php(2947): Model->getDataSource()
#2 /var/www/books/lib/Cake/Model/Model.php(2919): Model->_readDataSource('all', Array)
#3 /var/www/books/app/Controller/BookController.php(19): Model->find('all')
#4 [internal function]: BookController->index('home')
#5 /var/www/books/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(BookController), Array)
#6 /var/www/books/lib/Cake/Routing/Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/books/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(BookController), Object(CakeRequest))
#8 /var/www/books/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-09-30 21:38:36 Error: [MissingTableException] Table books for model Book was not found in datasource default.
Exception Attributes: array (
  'table' => 'books',
  'class' => 'Book',
  'ds' => 'default',
)
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Model/Model.php(3551): Model->setSource('books')
#1 /var/www/books/lib/Cake/Model/Model.php(2947): Model->getDataSource()
#2 /var/www/books/lib/Cake/Model/Model.php(2919): Model->_readDataSource('all', Array)
#3 /var/www/books/app/Controller/BookController.php(19): Model->find('all')
#4 [internal function]: BookController->index('home')
#5 /var/www/books/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(BookController), Array)
#6 /var/www/books/lib/Cake/Routing/Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/books/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(BookController), Object(CakeRequest))
#8 /var/www/books/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-09-30 21:38:37 Error: [MissingTableException] Table books for model Book was not found in datasource default.
Exception Attributes: array (
  'table' => 'books',
  'class' => 'Book',
  'ds' => 'default',
)
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/Model/Model.php(3551): Model->setSource('books')
#1 /var/www/books/lib/Cake/Model/Model.php(2947): Model->getDataSource()
#2 /var/www/books/lib/Cake/Model/Model.php(2919): Model->_readDataSource('all', Array)
#3 /var/www/books/app/Controller/BookController.php(19): Model->find('all')
#4 [internal function]: BookController->index('home')
#5 /var/www/books/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(BookController), Array)
#6 /var/www/books/lib/Cake/Routing/Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/books/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(BookController), Object(CakeRequest))
#8 /var/www/books/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-09-30 21:43:02 Error: [MissingViewException] View file "/var/www/books/app/View/Book/index.ctp" is missing.
Exception Attributes: array (
  'file' => '/var/www/books/app/View/Book/index.ctp',
)
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/View/View.php(468): View->_getViewFileName(NULL)
#1 /var/www/books/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#2 /var/www/books/lib/Cake/Routing/Dispatcher.php(198): Controller->render()
#3 /var/www/books/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(BookController), Object(CakeRequest))
#4 /var/www/books/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-09-30 21:43:03 Error: [MissingViewException] View file "/var/www/books/app/View/Book/index.ctp" is missing.
Exception Attributes: array (
  'file' => '/var/www/books/app/View/Book/index.ctp',
)
Request URL: /books/
Stack Trace:
#0 /var/www/books/lib/Cake/View/View.php(468): View->_getViewFileName(NULL)
#1 /var/www/books/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#2 /var/www/books/lib/Cake/Routing/Dispatcher.php(198): Controller->render()
#3 /var/www/books/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(BookController), Object(CakeRequest))
#4 /var/www/books/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
